version: "3.8"


services:
  web:
    build: .  # Build the Docker image from the current directory
    env_file:
      - .env
    ports:
      - 3000:3000  # Map host port 3000 to container port 3000
    volumes:
      - .:/usr/src/app  # Mount the current directory as a volume inside the container
    command: go run cmd/main.go -b 0.0.0.0 # Start Go webserver 
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=$(DB_USER)
      - POSTGRES_PASSWORD=$(DB_PASSWORD)
      - POSTGRES_DB=$(DB_NAME)
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: